apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceMonitors-crd.yaml
  - podMonitors-crd.yaml
  - probes-crd.yaml

patches:
  - target:
      kind: CustomResourceDefinition
    path: patch-strip-annotations.yaml
