apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openobserve-postgresql
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.5.5
    helm:
      valueFiles:
        - applications/postgresql/postgres-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openobserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
