apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openobserve
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: openobserve
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/openobserve/openobserve
    targetRevision: HEAD
    path: charts/helm-chart
    helm:
      values: |
        fullnameOverride: openobserve
        persistence:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
