apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Mani-72/OKD-ArgoCD
    targetRevision: main
    path: applications/prerequisites/prometheus-crds
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
