apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prerequisites
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/Mani-72/OKD-ArgoCD.git
    targetRevision: main
    path: applications/prerequisites
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
